/*
SQL seems to do implicit type conversions
*/
SELECT CEIL(AVG(SALARY) - AVG(REPLACE(CAST(SALARY AS CHAR), "0", ""))) FROM EMPLOYEES
SELECT CEIL(AVG(SALARY) - AVG(REPLACE(SALARY , "0", ""))) FROM EMPLOYEES
